# Site settings
title: liuxin-wq Blog
SEOTitle: 刘信的博客 | BY Blog
header-img: img/post-bg-desk.jpg
email: yuyuw759@gmail.com
description: life, how lonely like snow.
keyword: "lx, lx Blog, 刘信的博客, liuxin, 刘信, iOS, Apple, iPhone"
url: "http://liuxin-wq.github.io"          # your host, for absolute URL
baseurl: "/blog"      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/qiubaiying/qiubaiying.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "life, how lonely like snow."
sidebar-avatar:       # use absolute URL, seeing it's used in both `/` and `/about/`







# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important




# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



